name: 'Cypress E2E Tests'
on: workflow_dispatch

jobs:
  test:
      name: cypress-e2e-tests
      runs-on: ubuntu-latest
      
      steps:
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Setup-Amplify
        id: setenvname
        run: echo "##[set-output name=amplifyenvname;]$(echo ${GITHUB_HEAD_REF//[-_]/} | cut -c-10)"
        
      - name: deploy test environment
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: add_env
          amplify_env: ${{ steps.setenvname.outputs.amplifyenvname }}
          amplify_cli_version: '3.17.1-alpha.35'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AccessKey }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SecretKey }}
          AWS_REGION: us-east-1
        
      - name: Cypress E2E
        uses: cypress-io/github-action@v5.1.0
        with:
          start: npm start
          browser: chrome
          
        
        
